### ISSUE TITLE
Please provide an update site

### ISSUE THREAD

**Issue by stadler** [tesla/m2eclipse-egit#9]
Hi

It would be great if you could provide an update-site for this connector. Because now everyone has to checkout this project, create it's own update site and use this as site, which is really a pain.
Or now I just realized that after doing a 'mvn clean install' there is a site that is generated. But still it would be great if one could just link to an update site.

Also it would be great if you could update/create an m2eclipse marketplace updatesite for it so it can be easely found.

Thanks, Jacques

**Comment by mkalkov** [comment]
There are update sites here: http://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-egit/0.14.0/N/

**Comment by mkalkov** [comment]
Hm, according to https://git.eclipse.org/c/m2e/m2e-discovery-catalog.git/tree/org.eclipse.m2e.discovery.oss/connectors.xml#n237 the official site is https://repository.sonatype.org/content/sites/forge-sites/m2eclipse-egit/0.14.0/N/ but it hasn't been updated since 2011.

**Comment by mkalkov** [comment]
Hallelujah, I've found a working and up-to-date update site here: https://repository.takari.io/service/local/repositories/m2e.extras/content/m2eclipse-egit/0.14.0/N/LATEST/content.xml

**Comment by stadler** [comment]
And there is also:
http://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-egit/0.14.0/N/LATEST/
I think this should be enough to close this issue.

**Comment by mkalkov** [comment]
FYI, I've filed issue #13 about the broken http://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-egit/0.14.0/N/LATEST site.
